controllers:
    resource:
        path: ../../src/Application/Controller/
        namespace: App\Application\Controller
    type: attribute

api_controllers:
    resource:
        path: ../../src/Api/Controller/
        namespace: App\Api\Controller
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute
